### ISSUE TITLE
Multiple-CPUs supporting problem

### ISSUE THREAD

**Issue by wongxingjun** [systempanda200/RT-Xen#1]
Hello, I installed RT-xen successfully on my server and a problem really puzzled me a lot --
my server has 8 xeon cores and when I set dom0_max_vcpus=8 in my grub, the server couldn't boot in,and when  dom0_max_vcpus=4, it did work but another problem came, when more than 2 VMs(2 cores for each) were created ,the server crashed. I don't know what's the cause of this problem. I will appreciate a lot if someone can give me a hand. Thanks.

**Comment by systempanda200** [comment]
Thank you very much for using RT-Xen. 
Which branch and commit point did you use for the testing?
What is the error message the kernel dumps?
The RT scheduler has been pushed to Xen mainstream as the rtds scheduler.
Can you try the latest Xen code's rtds scheduler and see if it works? Thanks
